set_property SRC_FILE_INFO {cfile:C:/Users/kaman/Downloads/fpgasr/fpgasr1/fpgasr1.srcs/constrs_1/new/constraint.xdc rfile:../../../fpgasr1.srcs/constrs_1/new/constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N11 [get_ports clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports prediction]
